ACLOCAL_AMFLAGS ?= -I $(top_srcdir)/m4

QT_CXXFLAGS = -I/usr/include/Qt/ -I/usr/include/QtCore/ -I/usr/include/QtGui/ -I/usr/include/QtXml
QT_LIBS     = -L/usr/lib/qt4/

AM_CPPFLAGS = -DEXEC_PREFIX=\"$(exec_prefix)\" -DPREFIX=\"$(prefix)\" $(QT_CXXFLAGS) $(RTOS_CPPFLAGS) -DQT3_SUPPORT
AM_CXXFLAGS = -pipe -Wall $(QT_CXXFLAGS)
AM_LDFLAGS  = $(QT_LIBS) $(GSL_LIBS) $(RTOS_LDFLAGS)
AM_CFLAGS = $(AM_CXXFLAGS) 

if DEBUG
  AM_CXXFLAGS += -W -g
  AM_CPPFLAGS += -DDEBUG
else
  AM_CXXFLAGS += -O2
endif
