#!/bin/sh
#
# hotplug script for USBDUXFAST. Apr 21 2007. 
# berndporr@f2s.com
#
#
#
#look for comedi config
COMEDI_CONFIG=
#
if [ -e /usr/local/sbin/comedi_config ]; then
	COMEDI_CONFIG=/usr/local/sbin/comedi_config
fi
if [ -e /usr/sbin/comedi_config ]; then 
        COMEDI_CONFIG=/usr/sbin/comedi_config
fi
if [ -e /sbin/comedi_config ]; then 
        COMEDI_CONFIG=/sbin/comedi_config
fi
#
#
# default location
USBDUX_FIRMWARE=/lib/firmware/usbduxfast_firmware.hex
#
#
#
#
#
# If you have more than one device please add/uncomment
# 
# just to make sure we remove the comedi device
$COMEDI_CONFIG -r /dev/comedi0
# $COMEDI_CONFIG -r /dev/comedi1
#
# connecting the comedi device comedi0 with the module usbdux
$COMEDI_CONFIG --read-buffer 512 -i $USBDUX_FIRMWARE /dev/comedi0 usbduxfast
# $COMEDI_CONFIG /dev/comedi1 usbduxfast
#
#
