#! /bin/bash

### BEGIN INIT INFO
# Provides:          rtxi_load_analogy
# Required-Start:    $all 
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Load analogy at boot
# Description: Find the bus ID for the NI DAQ and use the address to load the analogy driver on startup
### END INIT INFO

#
# The Real-Time eXperiment Interface (RTXI)
# 
# Copyright (C) 2011 Georgia Institute of Technology, University of Utah, Weill
# Cornell Medical College
#
# This program is free software: you can redistribute it and/or modify it under
# the terms of the GNU General Public License as published by the Free Software
# Foundation, either version 3 of the License, or (at your option) any later
# version.
#
# This program is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
# FOR A PARTICULAR PURPOSE. See the GNU General Public License for more
# details.
#
# You should have received a copy of the GNU General Public License along with
# this program. If not, see <http://www.gnu.org/licenses/>.
#

# get pci bus address of card
bus_addr=$(lspci | grep National | awk '{print$1}' | colrm 2)

# parse address
val=$(lspci | grep National | awk '{print$1}' | tr ':' ',' | sed 's/.\{2\}$//' | tr --delete '0')

# setup load value for command
load_val=${bus_addr}x${val}

# call configuration to load the card
#$(/usr/xenomai/sbin/analogy_config analogy0 analogy_ni_pcimio ${load_val})
$(/usr/xenomai/sbin/analogy_config analogy0 analogy_ni_pcimio)

# error check
if [ $? -eq 0 ]; then
	echo "Analogy device loaded."
else
	echo "ERROR: Analogy device loading failed."
fi

exit 0
