.TH comedi 7 ""
.SH NAME
\fBcomedi\fR - the Linux Control and Measurement Device Interface
.SH SYNOPSIS
\fB#include <comedi.h>\fR
.br
.SH DESCRIPTION
The \fBcomedi\fR package is a collection of hardware drivers and
library routines that can be used to communicate with a variety of
data acquisition boards, including A/D converters, D/A converters,
digital I/O and timers.

.br
.SH OTHER DOCUMENTATION

Hardware and driver configuration, and device-specific information,
can be found in the \fBcomedi\fR souce, in the file
Documentation/comedi/drivers.txt.

.br
Programming documentation for comedilib can be found in
/usr/share/doc/comedilib, or also at http://www.comedi.org/comedi.

.SH SEE ALSO

\fBcomedi_config\fR(8),
\fBcomedi_calibrate\fR(8)

.SH VERSION

0.7.x

.SH AUTHOR

David Schleef, <ds@schleef.org>

