#!/usr/bin/env ruby

require 'comedi'
require 'getoptlong'
require 'common'

include Comedi

parse_options

begin
    dev = Comedi::open($filename)
rescue
    comedi_perror($filename)
    exit 1
end

if $verbose
    print "measuring device=#{$filename} subdevice=#{$subdevice}"
    print " channel=#{$channel} range=#{$range}"
    print " analog reference=#{$aref}\n"
end

begin
    data = dev.data_read($subdevice, $channel, $range, $aref)
rescue
    comedi_perror($filename)
    exit 1
end
puts data

exit 0
