
include comedi_kbuild.inc

obj-m += comedi.o
comedi-y := comedi_fops.o proc.o range.o drivers.o comedi_ksyms.o
comedi-$(CONFIG_COMEDI_RT) += rt_pend_tq.o rt.o
comedi-$(CONFIG_COMPAT) += comedi_compat32.o

obj-y += kcomedilib/
obj-y += drivers/

