#! /bin/sh

if [ -r ./shared ] ; then . ./shared ; else . /etc/pcmcia/shared ; fi

# Get device attributes
get_info $DEVICE

# Load site-specific settings
start_fn () { return; }
stop_fn () { return; }
. $0.opts

case "$ACTION" in

'start')

    #echo /usr/sbin/comedi_config /dev/comedi0 $2
    PATH=/sbin:/usr/sbin:/usr/local/sbin:$PATH;
    comedi_config /dev/comedi0 $2

    start_fn $DEVICE
    ;;

'stop')

    stop_fn $DEVICE

    ;;

'check')
    ;;

'cksum')
    ;;

'restart')
    ;;

'suspend'|'resume')
    ;;

*)
    usage
    ;;

esac

exit 0



