#!/bin/bash

bus_addr=$(lspci | grep National | awk '{print$1}' | colrm 2)

val=$(lspci | grep National | awk '{print$1}' | tr ':' ',' | sed 's/.\{2\}$//' | tr --delete '0')

load_val=${bus_addr}x${val}

#echo "DAQ card PCI address is: ${load_val}"

$(sudo analogy_config analogy0 analogy_ni_pcimio ${load_val})

if [ $? -eq 0 ]; then
	echo "Analogy device loaded."
else
	echo "ERROR: Analogy device loading failed."
fi
